name: pengyun-infocenter
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.gitignore'
      - '.github/workflows/**.yml'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: zettastor/pengyun-root/.github/workflows/ubuntu20.yml@1.0-OS
